config/routes.rb
Rails.application.routes.draw do  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  resources :patients
  
  resources :doctors
  resources :appointments do
    resources :comments
  end
end

app/models/appointment.rb
# == Schema Information
#
# Table name: appointments
#
#  id         :bigint           not null, primary key
#  message    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  doctor_id  :bigint
#  patient_id :bigint
#
class Appointment < ApplicationRecord
  belongs_to :patient, class_name: 'User'
  belongs_to :doctor, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, as: :recipient, dependent: :destroy 

  validates :message, presence: true, length: {maximum: 500}
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_appointment, only: %i(edit show update)
  load_and_authorize_resource

  def index
    @appointments = User.find_by_id(current_user).appointments
  end
  
  def show
    @comments = @appointment.comments.order(created_at: :desc)
    mark_notifications_as_read
  end

  def new
    @appointment = Appointment.new
    @doctor = Doctor.all
  end

  def edit
    @doctor = Doctor.all
  end

  def create
    @appointment = Appointment.new appointment_params
    if @appointment.save
      flash[:success] = "Appointment Created"
      redirect_to appointments_url(@appointment)
    else
      flash[:notice] = "Something went wrong while trying to create appointment"
      render :new
    end
  end

  def update
    if @appointment.update(appointment_params)
      flash[:notice] = "Appointment has been Updated"
    else
      render :edit
    end
    redirect_to appointments_path
  end

  def destroy
    if @appointment.destroy
      flash[:success] = "Appointment Deleted"
      redirect_to appointments_path
    else
      flash[:notice] = "Appointment deletion was unsuccessful"
      redirect_to root_url
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:message, :doctor_id).merge(patient_id: current_user.id)
  end

  def find_appointment
    @appointment = Appointment.find(params[:id])
    
    return if @appointment

    flash[:danger] = t "Appointment finding was unsuccessful"
    redirect_to root_url
  end

  def mark_notifications_as_read
    if current_user
      notifications_to_mark_as_read = @appointment.notifications_as_appointment.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form_appointment.html.erb
<div class="card-body">
  <%= form_for @appointment do |f| %>
    <% if current_user.present? %>
      <div class="form-horizontal">
        <div class="form-group">
          <div class="col-md-8 offset-md-2">
            <%= f.label "last_name", class: "form-label" %>
            <%= f.text_field :last_name, class: "form-control",
            disabled: true, value: current_user.profile.last_name %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-8 offset-md-2">
            <%= f.label "first_name", class: "form-label" %>
            <%= f.text_field :first_name, class: "form-control", disabled: true,
            value: current_user.profile.first_name %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-8 offset-md-2">
            <%= f.label "phone", class: "form-label" %>
            <%= f.text_field :phone_patient, class: "form-control",disabled: true,
            value: current_user.profile.phone%>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-8 offset-md-2">
            <%= f.label "email", class: "form-label" %>
            <%= f.email_field :email, class: "form-control",
            disabled: true, value: current_user.email %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-8 offset-md-2">
            <%= f.hidden_field  :patient_id, :value => current_user.id, class: "form-control"%>
          </div>
        </div>
    <% end %>
        <div class="form-group">
          <div class="col-md-8 offset-md-2">
            <%= f.label "doctor", class: "form-label"%>
            <%= f.select :doctor_id, @doctor.map { |d| [d.email, d.id] }, {include_blank: true}, {class: "form-control"}%>
          </div> 
        </div>
        <div class="form-group">
          <div class="col-md-8 offset-md-2">
            <%= f.label "message" , class: "form-label"%>
            <%= f.text_area :message, placeholder: ("message"), class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-8 text-center">
            <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/appointments/_table_appointment_list.html.erb
<table id="example2" class="table table-bordered table-hover text-center">
  <thead>
    <tr class="background-color">
      <th><%= t "doctor" %></th>
      <th><%= t "patient" %></th>
      <th><%= t "message" %></th>
      <th><%= t "create date" %></th>
      <th class="action-head"><%= t "action" %></th>
    </tr>
  </thead>

  <tbody>
    <% if @appointments.present? %>
      <% @appointments.each do |appointment| %>
        <tr class="trow">
          <td><%= appointment.doctor.email %></td>
          <td><%= appointment.patient.profile.last_name %></td>
          <td><%= appointment.message %></td>
          <td><%= appointment.created_at %></td>
          <td><%= link_to 'Show', appointment %></td>        
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/appointments/edit.html.erb
<br> 
<% provide :title, t("Edit appointment") %>
<div class="container">
  <div class="row text-center">
    <div class="col">
      <h1><%= t "Edit appointment" %></h1>
      <div class="breadcroumb_link">
        <%= link_to t("all appoitments"), appointments_url %>/<%= t "Edit appointment" %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-8 col-lg-2">
      <%= render "appointments/form_appointment" %>
    </div>
  </div>
</div>

app/views/appointments/index.html.erb
<br> 
<% provide :title, t("appointment_list") %>
<div class="container container_appointment_list">
  <div class="card-header padding-card">
    <h1 class="card-title color-list">
      <%= t "appointment_list"%>
    </h1>
  </div>
  <div class="card-body">
    <%= render "table_appointment_list" %>
  </div>
</div>

app/views/appointments/new.html.erb
<br/> 
<% provide :title, t("appointment") %>
<div class="container" style="margin-top: 50px;">
  <div class="row text-center">
    <div class="col">
      <h1><%= t "appointment" %></h1>
      <div class="breadcroumb_link">
        <%= link_to t("home"), root_url %>/<%= t "appointment" %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row justify-content-end">
    <div class="col-lg-6 col-md-12">
      <%= image_tag 'home/contact_form.png', class: "from-left d-none d-lg-block"%> 
    </div>
    <div class="col-xl-6 col-lg-6">
      <%= render "appointments/form_appointment" %>
    </div>
  </div>
</div>

app/views/appointments/show.html.erb
<br> 
<% provide :title, t("Appointment") %>
<div class="container">
  <div class="row text-center">
    <div class="col">
      <h1><%= t "Appointment" %></h1>
      <div class="breadcroumb_link">
        <%= link_to t("all appoitments"), appointments_url %>/<%= t "Appointment" %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-8 col-lg-2">
      <div class="container my-5">
        <div class="card bg-light shadow p-3 mb-5 rounded fs-5">
          <div class="row">
            <div class="col">
                <h2 class="text-center">
                <%= @appointment.message%>
                </h2>
            </div>
          </div>  
          <div class="row my-1">
            <div class="col-sm-2">
                Create date
            </div>
            <div class="col-sm-10">
                <div class="text-center">
                <%= @appointment.created_at %>
                </div>
            </div>
          </div>
          <div class="btn-group pb-2">
            <%= link_to "Back", appointments_path, class: "btn btn-secondary position-relative" %>
            <% if can? :manage, Appointment %>
              <%= link_to "Edit", edit_appointment_path, class: "btn btn-outline-warning position-relative" %>
              <%= button_to "Destroy this appointment", appointment_path(@appointment), method: :delete, class: "btn btn-outline-danger position-relative" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <%= render 'comments/form', appointment: @appointment %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', appointment: @appointment, comment: comment %>
  <% end %>
</div>